### ISSUE TITLE
Fuzz testing round 3: Roundtrip

### ISSUE THREAD

**Issue by squeek502** [ianic/deflate#8]
Nice work on the fixes so far, the decompress fuzzer is now running cleanly (~3 hours of fuzzing without any new crashes so far).

I've now run [a fuzzer](https://github.com/squeek502/flate/blob/fuzzing/test/fuzz_roundtrip.zig) that takes the input data and runs it through `flate.raw.compress` and then the result of that through `flate.raw.decompressor` and then checks that the final result is the same as the original input.

Failing inputs found while fuzz testing for ~2 hours:

[flate-fuzz-roundtrip-20230209-1.zip](https://github.com/ianic/flate/files/14228347/flate-fuzz-roundtrip-20230209-1.zip)

Code that can reproduce the failures:

```zig
const std = @import("std");
const flate = @import("flate");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer std.debug.assert(gpa.deinit() == .ok);
    const allocator = gpa.allocator();

    // Read the data from stdin
    const stdin = std.io.getStdIn();
    const data = try stdin.readToEndAlloc(allocator, std.math.maxInt(usize));
    defer allocator.free(data);

    var fbs = std.io.fixedBufferStream(data);
    const reader = fbs.reader();

    // Compress the data
    var buf = std.ArrayList(u8).init(allocator);
    defer buf.deinit();
    // TODO: vary the level
    try flate.raw.compress(reader, buf.writer(), .default);

    // Now try to decompress it
    var buf_fbs = std.io.fixedBufferStream(buf.items);
    var inflate = flate.raw.decompressor(buf_fbs.reader());
    const inflated = inflate.reader().readAllAlloc(allocator, std.math.maxInt(usize)) catch {
        return;
    };
    defer allocator.free(inflated);

    try std.testing.expectEqualSlices(u8, data, inflated);
}
```

**Comment by ianic** [comment]
Thanks, this exposed two really important bugs.

I saw your note:  `// TODO: vary the level`
[Here](https://github.com/ianic/flate/blob/main/bin/roundtrip.zig) is version which iterates over all levels including two special cases huffman only and stored only compression.

**Comment by squeek502** [comment]
Awesome!

My current understanding (but I could totally be wrong) is that fuzz testing is best when each input can be processed as fast as possible, so instead of compressing each input at every possible level, I've instead gone with choosing a level pseudo-randomly using a hash of the input data + a separate 'huffman only' fuzzer and a 'store only' fuzzer:

https://github.com/squeek502/flate/commit/63cb7fca4f5a20624ac1b336e5668a5fec3fa587

With the latest changes, all of the current fuzzers are running cleanly so far (but just started fuzzing, will let them run for a while now).

---

The last bit of fuzz testing I'm planning is using [`puff.c`](https://github.com/madler/zlib/tree/develop/contrib/puff) as an 'oracle' and making sure both the output and errors of `flate` match `puff.c` (if it makes sense to, otherwise, I'll just make sure that `flate` and `puff.c` both accept/reject the same inputs).

Here's the implementation of that I've used in the past: https://github.com/squeek502/zig-std-lib-fuzzing/blob/master/fuzzers/deflate-puff.zig
