### ISSUE TITLE
Fuzz testing round 4: Roundtrip followup

### ISSUE THREAD

**Issue by squeek502** [ianic/deflate#9]
Follow up to #8. Found some failures when running the roundtrip and roundtrip_huffman fuzzer:

[flate-fuzz-roundtrip-20230210-1.zip](https://github.com/ianic/flate/files/14231521/flate-fuzz-roundtrip-20230210-1.zip)
[flate-fuzz-roundtrip-huffman-20230210-1.zip](https://github.com/ianic/flate/files/14231522/flate-fuzz-roundtrip-huffman-20230210-1.zip)

The failures can be reproduced by running the inputs through https://github.com/ianic/flate/blob/main/bin/roundtrip.zig (since it tests all compression levels + huffman only + store only).

**Comment by ianic** [comment]
Great finding. 
I was mishandling  bit stream byte boundary during flushing. Resulted in adding few bits of padding if not at byte boundary.
Thanks.
